services:
  - type: web
    name: student-mess-backend
    runtime: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_URI
        value: mongodb+srv://studentmess:SecurePass2024@cluster0.mongodb.net/studenthotel
      - key: JWT_SECRET
        value: student-mess-ultra-secure-jwt-secret-production-2024-deployment
      - key: JWT_REFRESH_SECRET
        value: student-mess-refresh-token-ultra-secure-production-2024-deployment
      - key: JWT_EXPIRES_IN
        value: 1h
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: FRONTEND_URL
        value: https://mohansaina.github.io/student-mess-app
      - key: UPLOAD_PATH
        value: ./uploads
      - key: MAX_FILE_SIZE
        value: 5242880
      - key: USE_S3
        value: false
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: BCRYPT_SALT_ROUNDS
        value: 12

databases:
  - name: student-mess-db
    plan: free